################### Imports and Setup #########################################
# Import librabries
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from scipy.stats import chi2_contingency, ttest_ind
import warnings; warnings.filterwarnings('ignore')

# Standardize plots
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

################### Function Definition #######################################

""" Load Dataset ***********************************************************
Purpose: Reads .csv dataset into pandas dataframe

Inputs: filepath - file to be read in
    
Outputs: df - dataset in dataframe format

----------------------------------------------------------------------------"""

def load_dataset(filepath):
    # Use specified columns to read in Age, Gender, Workout Type, Workout
    # Duration, and Calories Burned
    df = pd.read_csv(filepath, usecols=[2, 3, 5, 6, 7])
    return df

""" Clean Dataset *************************************************************
Purpose: Clean raw dataset, create Calories Per Minute feature

Inputs: df - dataset consisting workout metrics
    
Outputs: df - cleaned dataset to be analyzed
        df_male - cleaned dataset to be analyzed consisting of male data
        df_female - cleaned dataset to be analyzed consisting of female data
        df_adults - cleaned dataset consisting of both genders together in one
        dataframe. Needed for one of the visualizations generated by
        create_visualizations.

----------------------------------------------------------------------------"""

def clean_dataset(df):
    # Remove missing values
    df = df.dropna()
    
    # Clean strings to title format
    df.columns = [col.title().replace("_", " ") for col in df.columns]
    df['Gender'] = df.Gender.str.title()
    
    # We want to keep the HIIT elements uppercase, all others title case
    df['Workout Type'] = df['Workout Type'].apply( lambda x: x.upper() if
                                                  str(x).isupper() else
                                                  x.title())
    
    # Add calories per minute feature
    df['Calories Per Minute'] = df['Calories Burned'] / df[\
                                                    'Workout Duration Minutes']
    # Filter out 'Other' values for gender
    df = df[df['Gender'] != 'Other']
    
    # Bin ages into age groups
    age_bins = [17, 34, 64]
    age_groups = ['Young Adult', 'Adult']
    df['Age Group'] = pd.cut(df['Age'], bins = age_bins, labels=age_groups)

    # Separate by gender, retain only 'Male' and 'Female' data
    df_male = df[df['Gender'] == 'Male']
    df_female = df[df['Gender'] == 'Female']
    
    return df, df_male, df_female

""" Create Visualizations *****************************************************
Purpose: Generate visualizations to illustrate insights from the dataset.

Inputs: df - dataframe assumed to be specific to gender
        gender - which gender is currently being analyzed (needed for plotting)
        df_a - dataframe consisting of both genders in the same dataframe
    
Outputs: Generates bar graphs showing workout type preferences as well as 
        stacked density plots for calories burned per minute by age group and 
        by workout type.

----------------------------------------------------------------------------"""

def plot_workout_by_gender(df, gender):
    # Set style
    sns.set_style("whitegrid")
    colors = sns.color_palette("Set2")
    
    # 1. Workout Type Preference by Gender
    plt.figure(figsize=(10, 6))
    crosstab_gender = pd.crosstab(df['Gender'], df['Workout Type'],
                                  normalize='index') * 100
    crosstab_gender.plot(kind='bar', color=colors, width=0.7)
    plt.title(f'{gender} Workout Type Preference by Gender (%)',
              fontsize=14, pad=20)
    plt.ylabel('Percentage of Workouts')
    plt.xlabel('Gender')
    plt.xticks(rotation=0)
    plt.legend(title='Workout Type', bbox_to_anchor=(1.05, 1),
               loc='upper left')
    plt.tight_layout()
    #plt.savefig('../reports/figures/workout_type_by_gender.png', dpi=300,
        #bbox_inches='tight')
    plt.show()
    plt.close()
    
    return

def plot_workout_by_age_group(df, gender):
    # Set style
    sns.set_style("whitegrid")
    colors = sns.color_palette("Set2")
    
    plt.figure(figsize=(12, 6))
    crosstab_age = pd.crosstab(df['Age Group'], df['Workout Type'],
                               normalize='index') * 100
    crosstab_age.plot(kind='bar', color=colors, width=0.7)
    plt.title(f'{gender} Workout Type Preference by Age Group (%)',
              fontsize=14, pad=20)
    plt.ylabel('Percentage of Workouts')
    plt.xlabel('Age Group')
    plt.xticks(rotation=0)
    plt.legend(title='Workout Type', bbox_to_anchor=(1.05, 1),
               loc='upper left')
    plt.tight_layout()
    #plt.savefig('../reports/figures/workout_type_by_age.png', dpi=300,
        #bbox_inches='tight')
    plt.show()
    plt.close()
    
    return 

def plot_cpm_by_gender(df, gender):
    # 3. CPM Density by Age Group for Each Gender
    plt.figure(figsize=(11, 7))
    sns.kdeplot(data=df, x='Calories Per Minute', hue='Age Group', 
                fill=True, alpha=0.35, linewidth=2.5, common_norm=False,
                    palette='Set2')
    plt.title(f'Calories Per Minute Distribution by Age Group ({gender}s)',
              fontsize=14)
    plt.xlabel('Calories Per Minute')
    plt.ylabel('Density')
    plt.legend(title='Age Group')
    plt.tight_layout()
    #plt.savefig('../reports/figures/cpm_density_by_age_overlaid.png',
        #dpi=300, bbox_inches='tight')
    plt.show()
    plt.close()
    
    return

def plot_cpm_by_workout_type(df, gender):
    # Set style
    sns.set_style("whitegrid")
    colors = sns.color_palette("Set2")
    
    # Plot distribution of Calories per minute by Workout Type
    p = sns.displot(
        data=df, 
        x='Calories Per Minute', 
        hue='Workout Type', 
        multiple='stack',
        kind='kde',
        palette=colors,
        edgecolor='white'
    )
    p.figure.suptitle(f'{gender} Calories Per Minute Density by Workout Type')
    plt.tight_layout()
    #plt.savefig('../reports/figures/cpm_density_by_workout_type.png',
        #dpi=300, bbox_inches='tight')
    plt.show()
    plt.close()
    
    return

""" Stats *********************************************************************
Purpose: Run statistical testing to find correlations in the dataset.

Inputs: df - dataframe containing dataset
    
Outputs: Generates chi-square and T-test results and delivers determination 
of any associations within the dataset.
----------------------------------------------------------------------------"""

def stats(df):
    # Chi-Square Test Workout Type vs. Gender
    contingency = pd.crosstab(df['Workout Type'], df['Gender'])
    chi2, p, dof, expected = chi2_contingency(contingency)
    
    # T-Test for Calories Per Minute
    male_cpm = df[df['Gender'] == 'Male']['Calories Per Minute']
    female_cpm = df[df['Gender'] == 'Female']['Calories Per Minute']
    
    t_stat, p_val = ttest_ind(male_cpm, female_cpm, equal_var=False)
    
    return


################### Execution #################################################
# Load and Clean the Dataset
df_raw = load_dataset("daily_gym_attendance_workout_data.csv")
df, df_male, df_female = clean_dataset(df_raw)

print(f"Dataset shape after cleaning: {df.shape}")
print(f"Male samples: {len(df_male)}, Female samples: {len(df_female)}")

## Exploratory Visualizations
# 1. Plot Workout Preference by Gender (Males)
plot_workout_by_gender(df_male, 'Male')

# 2. Plot Workout Preference by Gender (Females)
plot_workout_by_gender(df_female, 'Female')

# 3. Plot Workout Preference by Age Group (Males)
plot_workout_by_age_group(df_male, 'Male')

# 4. Plot Workout Preference by Age Group (Females)
plot_workout_by_age_group(df_female, 'Female')

# 5. Plot Calories per Minute by Age Group (Males)
plot_cpm_by_gender(df_male, 'Male')

# 6. Plot Calories per Minute by Age Group (Females)
plot_cpm_by_gender(df_female, 'Female')

# 7. Plot Calories per Minute by Workout Type (Males)
plot_cpm_by_workout_type(df_male, 'Male')

# 8. Plot Calories per Minute by Workout Type (Females)
plot_cpm_by_workout_type(df_female, 'Female')

# Conduct chi-square and t-testing on dataset
stats(df)
