import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import chi2_contingency, ttest_ind, f_oneway
import warnings; warnings.filterwarnings('ignore')

################### Function Definition #######################################

""" Load Dataset ***********************************************************
Purpose: Reads .csv dataset into pandas dataframe

Inputs: filepath - file to be read in
    
Outputs: df - dataset in dataframe format

----------------------------------------------------------------------------"""

def load_dataset(filepath):
    # Use specified columns to read in Age, Gender, Workout Type, Workout
    # Duration, and Calories Burned
    df = pd.read_csv(filepath, usecols=[2, 3, 5, 6, 7])
    return df

""" Clean Dataset *************************************************************
Purpose: Clean raw dataset, create Calories Per Minute feature

Inputs: df - dataset consisting workout metrics
    
Outputs: df - cleaned dataset to be analyzed
        df_male - cleaned dataset to be analyzed consisting of male data
        df_female - cleaned dataset to be analyzed consisting of female data
        df_adults - cleaned dataset consisting of both genders together in one
        dataframe. Needed for one of the visualizations generated by
        create_visualizations.

----------------------------------------------------------------------------"""

def clean_dataset(df):
    # Check for and remove missing values
    print('\nCheck null values:\n', df.isna().sum())
    df = df.dropna()
    
    # Clean strings to title format
    df.columns = [col.title().replace("_", " ") for col in df.columns]
    df['Gender'] = df.Gender.str.title()
    
    # We want to keep the HIIT elements uppercase, all others title case
    df['Workout Type'] = df['Workout Type'].apply( lambda x: x.upper() if \
                                                  str(x).isupper() else \
                                                  x.title())
    
    # Add calories per minute feature
    df['Calories Per Minute'] = df['Calories Burned'] / df[\
                                                    'Workout Duration Minutes']
    # Filter out 'Other' values for gender
    df = df[df['Gender'] != 'Other']
    
    # Bin ages into age groups
    age_bins = [17, 34, 64, 200]
    age_groups = ['Young Adult', 'Adult', 'Senior']
    df['Age Group'] = pd.cut(df['Age'], bins = age_bins, labels=age_groups)
    
    # Categorize Workout Type for later analysis
    df['Quantified Workout Type'] = df['Workout Type'].astype('category')

    # Separate by gender, retain only 'Male' and 'Female' data
    df_male = df[df['Gender'] == 'Male']
    print('\nMale samples\n', df_male['Gender'].count())
    df_female = df[df['Gender'] == 'Female']
    print('\nFemale samples\n', df_female['Gender'].count())
    
    # Check for consistency in categorical features
    print('\nGender values: ', df_male['Gender'].unique(), df_female[\
                                                            'Gender'].unique())
    print('\nWorkout Type values: ', df['Workout Type'].unique())
    df_adults = df[df['Age Group'] != 'Seniors']
    
    return df, df_male, df_female, df_adults

""" Explore Dataset ***********************************************************
Purpose: Generate statistics from the dataset as well as box and density plots
        to begin identifying trends.

Inputs: df - dataset consisting of one gender's exercise metrics 
        gender - the gender currently being analyzed
Outputs: Initial visualizations of the dataset.

----------------------------------------------------------------------------"""

def explore_dataset(df, gender):
    
    # Print summary information
    print('\nSamples By Age:\n', df['Age Group'].value_counts())
    
    # Display summary statistics for all columns
    pd.set_option('display.max_columns', None)
    print('\nSummary Statistics\n', df.describe())
    pd.reset_option('display.max_columns')
    
    # View age group statistics:
    cols = ['Workout Duration Minutes', 'Calories Burned', \
            'Calories Per Minute']
    
    for col in cols:
        
        # Quartile boxplots
        ax = df.boxplot(column=col, by = 'Age Group')
        ax.get_figure().suptitle('')
        plt.title(f'{gender} {col} Quartiles')
        plt.ylabel(f'{col}')
        plt.show()
        
        # Plot densities
        print(f'\n{gender} {col} Age Group Statistics:\n', \
              df.groupby('Age Group', observed=True)[col].agg(['mean', 'std',\
                                                                'var']) )
        ax = df.groupby('Age Group', observed=True)[col].plot(\
                kind='density', title=f'{gender} {col} Density', legend=True)
        plt.xlabel(f'{col}')
        plt.tight_layout()
        plt.show()
    
    # Print statistics for workout type preferences (visualized in
    # create_visualizations function)
    print(f'\n{gender} Workout Type Preference (%):\n', df.groupby('Age Group')\
          ['Workout Type'].value_counts(normalize=True)*100, '\n')
        
    return

""" Create Visualizations *****************************************************
Purpose: Generate visualizations to illustrate insights from the dataset.

Inputs: df - dataframe assumed to be specific to gender
        gender - which gender is currently being analyzed (needed for plotting)
        df_a - dataframe consisting of both genders in the same dataframe
    
Outputs: Generates bar graphs showing workout type preferences as well as 
        stacked density plots for calories burned per minute by age group and 
        by workout type.

----------------------------------------------------------------------------"""

def create_visualizations(df, gender, df_a):
    # Normalize value_counts and generate percentage
    group = 100 * df.groupby('Age Group', observed=True)['Workout Type'].\
        value_counts(normalize=True).unstack() 
    
    # Streamline color palettes for plotting
    colors = sns.color_palette("Set2", n_colors=5)
    
    ax = group.plot(kind='bar', \
         title=f'{gender} Workout Type Preference Analysis', legend=True, \
             color=colors)
    plt.ylabel('Percent of Total Workouts')
    plt.xticks(rotation=45)
    plt.legend(bbox_to_anchor=(0.95, -0.01), loc='lower right')
    plt.tight_layout()
    plt.show()
    
    # Plot distribution of Calories per minute for Age Groups
    p = sns.displot(
        data=df, 
        x='Calories Per Minute', 
        hue='Age Group', 
        multiple='stack',
        kind='kde',
        palette='Set2',
        edgecolor='white'
    )
    p.figure.suptitle(f'{gender} Calories Per Minute Density')
    plt.tight_layout()
    plt.show()
    
    # Plot distribution of Calories per minute
    p = sns.displot(
        data=df, 
        x='Calories Per Minute', 
        hue='Quantified Workout Type', 
        multiple='stack',
        kind='kde',
        palette='Set2',
        edgecolor='white'
    )
    p.figure.suptitle(f'{gender} Calories Per Minute Density')
    plt.tight_layout()
    plt.show()
    
    return

""" Stats *********************************************************************
Purpose: Run statistical testing to find correlations in the dataset.

Inputs: df - dataframe containing dataset
    
Outputs: Generates chi-square and T-test results and delivers determination 
of any associations within the dataset.
----------------------------------------------------------------------------"""

def stats(df):
    print("*"*16, 'Statistical Testing', "*"*16)
    
    # Chi-Square Test
    print("\n1. Chi-Square Test: Workout Type vs Gender")
    contingency = pd.crosstab(df['Workout Type'], df['Gender'])
    chi2, p, dof, expected = chi2_contingency(contingency)
    print(f"Chi-square statistic: {chi2:.4f}")
    print(f"p-value: {p:.6f}")
    print("→ Significant association between Gender and Workout Preference" \
          if p < 0.05 else "→ No significant association")
    
    # T-Test for Calories Per Minute
    print("\n2. T-Test: Calories Per Minute by Gender")
    male_cpm = df[df['Gender'] == 'Male']['Calories Per Minute']
    female_cpm = df[df['Gender'] == 'Female']['Calories Per Minute']
    
    t_stat, p_val = ttest_ind(male_cpm, female_cpm, equal_var=False)
    print(f"T-statistic: {t_stat:.4f}")
    print(f"p-value: {p_val:.6f}")
    print("→ Males have significantly higher intensity" if p_val < 0.05 \
          else "→ No significant difference")
    
    return

################### Execution #################################################
print('\n++++++++++++++++++ Load, Clean Data ++++++++++++++++++')
df_raw = load_dataset("daily_gym_attendance_workout_data.csv")
df, df_male, df_female, df_adults = clean_dataset(df_raw)

print('\n+++++++++++++ Exploratory Data Analysis ++++++++++++++')
print('\n*********************** Males ************************')
explore_dataset(df_male, 'Male')
print('\n********************** Females ***********************')
explore_dataset(df_female, 'Female')
create_visualizations(df_male, 'Male', df_adults)
create_visualizations(df_female, 'Female', df_adults)
stats(df)
