'''
Author: Dennis Toups
Date: 24 June 2026
'''

################### Imports and Setup #########################################
# Import librabries
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from scipy.stats import chi2_contingency, ttest_ind
import warnings; warnings.filterwarnings('ignore')

# Standardize plots
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

################### Function Definition #######################################

""" Load Dataset ***********************************************************
Purpose: Reads .csv dataset into pandas dataframe

Inputs: filepath - file to be read in
    
Outputs: df - dataset in dataframe format

----------------------------------------------------------------------------"""

def load_dataset(filepath):
    # Use specified columns to read in Age, Gender, Workout Type, Workout
    # Duration, and Calories Burned
    df = pd.read_csv(filepath, usecols=[0, 1, 7, 8, 9])
    return df

""" Clean Dataset *************************************************************
Purpose: Clean raw dataset, create Calories Per Minute feature

Inputs: df - dataset consisting workout metrics
    
Outputs: df - cleaned dataset to be analyzed
        df_male - cleaned dataset to be analyzed consisting of male data
        df_female - cleaned dataset to be analyzed consisting of female data
        df_adults - cleaned dataset consisting of both genders together in one
        dataframe. Needed for one of the visualizations generated by
        create_visualizations.

----------------------------------------------------------------------------"""

def clean_dataset(df):
    
    # Clean strings to title format
    df.columns = [col.title().replace("_", " ") for col in df.columns]
    df['Gender'] = df.Gender.str.title()
    
    # We want to keep the HIIT elements uppercase, all others title case
    df['Workout Type'] = df['Workout Type'].apply( lambda x: x.upper() if
                                                  str(x).isupper() else
                                                  x.title())
    
    # Transform Session Duration from hours to minutes, rename
    df['Session Duration (minutes)'] = 60 * df['Session Duration (Hours)']
    
    # Add calories per minute feature
    df['Calories Per Minute'] = df['Calories Burned'] / df[\
                                                    'Session Duration (minutes)']
    # Filter out invalid values for gender
    df = df[df['Gender'].isin(['Male', 'Female'])]
    
    df = df.dropna().copy()  # Drop any real missing values
    
    # Create Age Group bins
    df['Age Group'] = pd.cut(df['Age'], 
                             bins=[17, 34, 64], 
                             labels=['Young Adult', 'Adult'])
    # Remove any rows that were not binned (including 'nan')
    df = df[df['Age Group'].notna()].copy()
    
    # Convert to string
    df['Age Group'] = df['Age Group'].astype(str)
    
    print(f"Final dataset shape after cleaning: {df.shape}")

    # Separate by gender
    df_male = df[df['Gender'] == 'Male']
    df_female = df[df['Gender'] == 'Female']
    
    return df, df_male, df_female

""" Plot Functions ************************************************************
Purpose: Generate visualizations to illustrate insights from the dataset.

Inputs: df - dataframe assumed to be specific to gender
        gender - which gender is currently being analyzed (needed for plotting)
    
Outputs: Misc plots illustrating workout preferences among age groups by
gender as well as kde plots for calories burned per minute also by gender and
age group.

----------------------------------------------------------------------------"""

def plot_workout_by_age_group(df, gender):
    # Set style
    sns.set_style("whitegrid")
    colors = sns.color_palette("Set2")
    
    crosstab_age = pd.crosstab(df['Age Group'], df['Workout Type'],
                               normalize='index') * 100
    ax = crosstab_age.plot(kind='bar', color=colors, width=0.7)
    
    for container in ax.containers:
        ax.bar_label(container, fmt='%.1f%%', label_type='edge', padding=3)
        
    # Add horizontal mean line
    mean_value = crosstab_age.values.mean()
    ax.axhline(y=mean_value, color='red', linestyle='--', linewidth=2, \
               label=f'Overall Mean ({mean_value:.1f}%)')
        
    # Add sample size annotation (n=xxx) below the legend
    sample_sizes = df['Age Group'].value_counts().sort_index()    
    text = "\n".join([f"{age}: n={count}" for age, count in 
                      sample_sizes.items()])
    plt.figtext(0.92, 0.15, text, fontsize=11, 
            bbox=dict(boxstyle="round", facecolor="white", alpha=0.8))
        
    plt.title(f'{gender} Workout Type Preference by Age Group (%)',
              fontsize=14, pad=20)
    plt.ylabel('Percentage of Workouts')
    plt.xlabel('Age Group')
    plt.xticks(rotation=0)
    plt.legend(title='Workout Type', bbox_to_anchor=(1.05, 1),
               loc='upper left')
    plt.tight_layout()
    #plt.savefig('../reports/figures/workout_type_by_age.png', dpi=300,
        #bbox_inches='tight')
    plt.show()
    plt.close()
    
    return 

def plot_cpm (df):
    # CPM by Workout Type, split by Age Group and Gender
    sns.catplot(
        data=df, 
        x='Workout Type', 
        y='Calories Per Minute',
        hue='Gender',
        col='Age Group',
        kind='box',
        height=5,
        aspect=1.1,
        palette='Set2',
        showfliers=False
        )

    plt.suptitle('Calories Per Minute by Workout Type, Age Group, and Gender', y=1.05)
    plt.xticks(rotation=45)
    plt.show()
    plt.close()
    
    return

""" Stats *********************************************************************
Purpose: Run statistical testing to find correlations in the dataset.

Inputs: df - dataframe containing dataset
    
Outputs: Generates chi-square and T-test results and delivers determination 
of any associations within the dataset.
----------------------------------------------------------------------------"""

def stats(df):
    results = []
    
    # Chi-Square Test Workout Type vs. Gender by Age Group
    for age_group in sorted(df['Age Group'].unique()):
        subset = df[df['Age Group'] == age_group]
        contingency = pd.crosstab(subset['Gender'], subset['Workout Type'])
        
        if contingency.shape[0] >= 2 and contingency.shape[1] >= 2:
            chi2, p, _, _ = chi2_contingency(contingency)
            results.append({
                'Test': 'Chi-square',
                'Group': f'Age Group: {age_group}',
                'Comparison': 'Gender vs Workout Type',
                'p-value': round(p, 4),
                'Significant': p < 0.05
            })
            
        print(f"Age Group: {age_group} ({len(subset)} samples)")
        print(f"   Chi-square p-value: {p:.4f} → {'Significant' if \
              p < 0.05 else 'Not significant'}")
        print(f"   Contingency Table:\n{contingency}")
        
    # T-tests by Age Group within Gender
    for gender in ['Male', 'Female']:
        subset = df[df['Gender'] == gender]
        young = subset[subset['Age Group'] == 'Young Adult']['Calories Per Minute']
        adult = subset[subset['Age Group'] == 'Adult']['Calories Per Minute']
        
        if len(young) >= 10 and len(adult) >= 10:
            _, p_val = ttest_ind(young, adult, equal_var=False)
            results.append({
                'Test': 'T-test',
                'Group': f'Gender: {gender}',
                'Comparison': 'Young Adult vs Adult (CPM)',
                'p-value': round(p_val, 4),
                'Significant': p_val < 0.05
            })
            
        print(f"Gender: {gender} ({len(subset)} total samples)")
        print(f"   Young Adult : n={len(young)}, Mean = {young.mean():.2f}")
        print(f"   Adult       : n={len(adult)}, Mean = {adult.mean():.2f}")
        print(f"   p-value     : {p_val:.4f} {'→ Significant difference' if \
              p_val < 0.05 else '→ No significant difference'}")
        
    return

################### Execution #################################################
# Load and Clean the Dataset
df_raw = load_dataset("gym_members_exercise_tracking.csv")
df, df_male, df_female = clean_dataset(df_raw)

print(f"Dataset shape after cleaning: {df.shape}")
print(f"Male samples: {len(df_male)}, Female samples: {len(df_female)}")

## Exploratory Visualizations
# 1. Plot Workout Preference by Age Group (Males)
plot_workout_by_age_group(df_male, 'Male')

# 2. Plot Workout Preference by Age Group (Females)
plot_workout_by_age_group(df_female, 'Female')

# 3. Plot Calories per Minute by Workout Type and Gender
plot_cpm(df)

## Conduct chi-square and t-testing on dataset
stats(df)
